version: 2.1

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.2xlarge+(2)
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run: nvidia-smi
      - run: nproc
    parallelism: 2


workflows:
  version: 2
  all:
    jobs:
      - build
